# Generated by Django 5.1.1 on 2024-09-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100)),
                ('system_name', models.CharField(max_length=100)),
                ('site_logo', models.ImageField(upload_to='uploads/')),
                ('favicon', models.FileField(upload_to='uploads/')),
                ('home_banner', models.ImageField(upload_to='uploads/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('footer_text', models.TextField()),
            ],
        ),
    ]
