# Generated by Django 5.1.1 on 2024-09-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.ImageField(upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='favicon',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='home_banner',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
